### ISSUE TITLE
"Index out of range" error from ole2 stream_reader

### ISSUE THREAD

**Issue by samstarling** [extrame/xls#7]
Apologies in advance, because I'm not particularly proficient with Go. I'm having a problem parsing an XLS file. Here's the error:

```
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/extrame/ole2.(*StreamReader).Read(0xc82006a1e0, 0xc90b242150, 0x4, 0x4, 0xe2300, 0x0, 0x0)
	/Users/samuelstarling/Development/go/src/github.com/extrame/ole2/stream_reader.go:34 +0x3a6
io.ReadAtLeast(0x424328, 0xc82006a1e0, 0xc90b242150, 0x4, 0x4, 0x4, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.1/libexec/src/io/io.go:298 +0xe6
io.ReadFull(0x424328, 0xc82006a1e0, 0xc90b242150, 0x4, 0x4, 0x4, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.1/libexec/src/io/io.go:316 +0x62
encoding/binary.Read(0x424328, 0xc82006a1e0, 0x4242d0, 0x2091a0, 0x108b20, 0xc820068590, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.1/libexec/src/encoding/binary/binary.go:216 +0x1336
github.com/extrame/xls.(*WorkBook).Parse(0xc820124000, 0x424350, 0xc82006a1e0)
	/Users/samuelstarling/Development/go/src/github.com/extrame/xls/workbook.go:44 +0x145
github.com/extrame/xls.newWorkBookFromOle2(0x424350, 0xc82006a1e0, 0x424350)
	/Users/samuelstarling/Development/go/src/github.com/extrame/xls/workbook.go:34 +0x127
github.com/extrame/xls.parse(0xc820092000, 0x7eb90, 0x7ed90, 0x137e88, 0x5, 0x0, 0x0, 0x0)
	/Users/samuelstarling/Development/go/src/github.com/extrame/xls/xls.go:46 +0x27c
github.com/extrame/xls.Open(0x161fa0, 0x32, 0x137e88, 0x5, 0x4b27, 0x0, 0x0)
	/Users/samuelstarling/Development/go/src/github.com/extrame/xls/xls.go:12 +0xa6
main.main()
	/Users/samuelstarling/Development/personal/xls-test/test.go:9 +0x48
exit status 2
```

I'm running code like this:

```
func main() {
    xlsFile, err := xls.Open("full.xls", "utf-8")
    if err != nil {
        panic(err)
    }
    fmt.Println(xlsFile)
}
```

Am I doing something wrong, or is there something up with the file?

Thanks!

**Comment by extrame** [comment]
Hi samstarling,

I make some update, so you can test if your problem solved.

If not, would you mind give me your xls file, maybe I can test it.

**Comment by samstarling** [comment]
@extrame Can I e-mail you the file that does not get parsed correctly?

**Comment by extrame** [comment]
Sure :-)

**Comment by extrame** [comment]
@samstarling Hi, could you email me the test xls file?

**Comment by extrame** [comment]
Fixed
